#!/bin/bash

ABBREV='rbenv-rubygems'
OWNER='jhsu802701'
DISTRO='debian'
SUITE='jessie'
DOCKER_IMAGE="$OWNER/$DISTRO-$SUITE-$ABBREV"
CONTAINER="container-$DISTRO-$SUITE-$ABBREV"
TGZ_FILE="$DISTRO-$SUITE-$ABBREV.tgz"

sh setup.sh $ABBREV $DOCKER_IMAGE $CONTAINER $TGZ_FILE '1083' '1080' '3003' '3000' '15435' '5432'
